---
title: "Weather Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

```{r, include=FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>%
  plot_ly(
    x = ~month, y = ~mean_tmax, color = ~name,
    mode = "lines+markers"
  ) %>%
  layout(
    title = "Average Max Temperature",
    yaxis = list(title = "Temperature (degrees C)"),
    xaxis = list(title = "Months")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
weather_df %>%
  plot_ly(
    x = ~tmax, color = ~name,
    type = "histogram", colors = "viridis") %>%
  layout(
    title = "Distribution of Max Temperature",
    xaxis = list(title = "Temperature (degrees C)")
  ) 
```

### Chart C

```{r}
weather_df %>%
  plot_ly(
    y = ~tmax, color = ~name,
    type = "box", colors = "viridis") %>%
  layout(
    title = "Distribution of Max Temperature",
    yaxis = list(title = "Temperature (degrees C)")
  ) 
```
